import {previousMonth,payrollReport,expiryItems} from './reporting.js';
import {isRecoveryLocation,mountRecovery} from './recovery.js?v=20260920-forgot';
import {mountForgotPassword} from './forgot-password.js';
import {assistantView} from './assistant.js';
import {config} from './config.js';
import {esc as E,today,money,hours,number,addDays,weekStart,recipeCost,proposeWeek,csv} from './core.js';
let payrollMonth=previousMonth(today()),deliveryState=null;
const demo=new URLSearchParams(location.search).get('demo')==='1';
const $=s=>document.querySelector(s), root=$('#app'),dialog=$('#dialog'),body=$('#dialog-body');
const recovering=isRecoveryLocation(location);
const sb=window.supabase?.createClient(config.url,config.key,{auth:{persistSession:!recovering,autoRefreshToken:true,detectSessionInUrl:true}});
let session=null,me=null,people=[],records=[],audit=[],page='today',month=today().slice(0,7),week=weekStart(today()),filter='',category='',pending=null,refreshing=false;
const labels={assistant:'Fraid pomocník',today:'Dnes',attendance:'Dochádzka',shifts:'Zmeny',recipes:'Receptúry',stock:'Sklad',checklists:'Checklisty',sales:'Tržby',notes:'Odkazy',team:'Tím',admin:'Administrácia',payroll:'Výplaty',settings:'Nastavenia',more:'Viac'};
const admin=()=>me?.role==='admin';
const list=k=>records.filter(r=>r.kind===k&&r.data.status!=='void');
const data=k=>list(k).map(r=>({...r.data,id:r.id,_version:r.version,_owner:r.owner_id}));
const rec=(k,id)=>records.find(r=>r.kind===k&&r.id===id);
const settings=()=>rec('settings','main')?.data||{};
const person=id=>people.find(p=>p.id===id);
const name=id=>person(id)?.name||'Pôvodný záznam';
const avatar=p=>`<img class="avatar" src="assets/IMG_${['pudlik','zaba','kuriatko','macicka','medvedik','tucniak','zirafa'].includes(p?.avatar)?p.avatar:'pudlik'}_happy.png" alt="">`;
const button=(text,action,id='',cls='')=>`<button class="${cls}" data-action="${action}" data-id="${E(id)}">${text}</button>`;
const empty=t=>`<div class="empty">${E(t)}</div>`;
const field=(label,n,value='',type='text',extra='')=>`<label>${label}<input name="${n}" type="${type}" value="${E(value)}" ${extra}></label>`;
const area=(label,n,value='')=>`<label class="full">${label}<textarea name="${n}">${E(value)}</textarea></label>`;
const select=(label,n,options,value)=>`<label>${label}<select name="${n}">${options.map(([v,t])=>`<option value="${E(v)}" ${String(v)===String(value)?'selected':''}>${E(t)}</option>`).join('')}</select></label>`;
const employeeOptions=()=>people.filter(p=>p.active).map(p=>[p.id,p.name]);
const badge=(t,c='')=>`<span class="badge ${c}">${E(t)}</span>`;
function toast(t){$('#status').textContent=t;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#status').textContent='',6500);}
function dateLabel(d){return new Intl.DateTimeFormat('sk-SK',{day:'numeric',month:'long',year:'numeric'}).format(new Date(d+'T12:00:00'));}
function header(title,desc='',actions=''){return `<div class="row between"><div><div class="eyebrow">FRAID / PREVÁDZKA</div><h1>${title}</h1><p class="muted">${desc}</p></div><div class="row">${actions}</div></div>`;}
function modal(title,html,submit,onSubmit){body.innerHTML=`<form id="editor"><div class="row between"><h2>${E(title)}</h2>${button('✕','close','','small')}</div><div class="formgrid">${html}</div><p id="form-error" class="error-text" role="alert"></p><div id="retry-area"></div><div class="actions">${button('Zavrieť','close')}${submit?`<button class="primary" type="submit">${E(submit)}</button>`:''}</div></form>`;body.querySelectorAll('button[data-action]').forEach(b=>b.type='button');if(!dialog.open)dialog.showModal();$('#editor').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget;const btn=form.querySelector('[type=submit]');try{btn.disabled=true;$('#form-error').textContent='';await onSubmit(Object.fromEntries(new FormData(form)),form);dialog.close();render();}catch(err){$('#form-error').textContent=err.message;$('#retry-area').innerHTML=pending?button('Overiť uloženie pôvodného zápisu','retry-write','','accent'):'';if(pending)$('#retry-area button').type='button';}finally{btn.disabled=false;}};}
async function loadRecords(){const rows=[];for(let offset=0;;offset+=500){const r=await sb.from('fraid_v2_records').select('*').order('kind').order('id').range(offset,offset+499);if(r.error)return r;rows.push(...r.data);if(r.data.length<500)return {data:rows,error:null};}}
async function refresh(){if(demo)return;const rr=await Promise.all([sb.from('fraid_v2_people').select('*'),loadRecords()]);for(const r of rr)if(r.error)throw r.error;people=rr[0].data;records=rr[1].data.sort((a,b)=>b.updated_at.localeCompare(a.updated_at));me=people.find(p=>p.user_id===session?.user.id&&p.active);if(admin()){const a=await sb.from('fraid_v2_audit').select('*').order('created_at',{ascending:false}).limit(150);if(a.error)throw a.error;audit=a.data;const ds=await sb.rpc('fraid_delivery_status');deliveryState=ds.error?null:ds.data;}}
const pendingKey=()=> 'fraid-v2-pending-'+session?.user.id;
function rememberPending(){try{pending?sessionStorage.setItem(pendingKey(),JSON.stringify(pending)):sessionStorage.removeItem(pendingKey());}catch{}}
async function write(p){if(demo)throw Error('Ukážka je iba na prezeranie. Žiadne údaje sa neukladajú.');if(!navigator.onLine)throw Error('Si offline. Formulár zostal vyplnený. Po pripojení skús uložiť znova.');
 if(pending)throw Error('Najprv over pôvodný nejasný zápis tlačidlom Overiť uloženie.');pending={...p,requestId:crypto.randomUUID()};rememberPending();toast('Ukladám…');const {data:out,error}=await sb.rpc('fraid_v2_write',{p:pending});if(error){if(error.code&&error.code!=='PGRST000'){pending=null;rememberPending();}throw error;}pending=null;rememberPending();toast('Uložené.');try{await refresh();}catch{toast('Uložené, ale prehľad sa nepodarilo obnoviť. Použi Obnoviť.');}return out;}
async function save(k,id,d,reason=''){const old=rec(k,id);return write({op:'save',kind:k,id:id||crypto.randomUUID(),version:old?.version||0,data:d,reason});}
function authView(message=''){root.innerHTML=`<main class="auth"><div class="brand"><img src="assets/FRAID_LOGO_ICON.png" alt="Fraid">Fraid</div><div class="card"><div class="eyebrow">VITAJ SPÄŤ</div><h1>Tvoja kaviareň.<br>Tvoj deň.</h1><p class="muted">Prihlás sa do prevádzky.</p><form id="auth" class="stack">${field('E-mail','email','','email','required autocomplete="username"')}${field('Heslo','password','','password','required minlength="12" autocomplete="current-password"')}<p id="auth-error" class="error-text" role="alert">${E(message)}</p><button class="primary" type="submit">Prihlásiť sa</button><button type="button" id="register">Vytvoriť účet</button></form><p class="auth-note">Nový účet musí po overení e-mailu schváliť administrátor a priradiť k profilu. Pôvodné údaje zostanú zachované.</p></div><p class="auth-note">Nová verzia · Prístup k údajom riadi databáza.</p></main>`;
 const forgot=document.createElement('a');forgot.href='?forgot=1';forgot.textContent='Zabudnuté heslo';forgot.id='forgot-password-link';$('#auth').append(forgot);
 forgot.onclick=e=>{e.preventDefault();const email=$('#auth').elements.email.value;history.pushState(null,'','?forgot=1');mountForgotPassword(sb,root,email);};
 $('#auth').onsubmit=e=>authenticate(e,false);$('#register').onclick=e=>authenticate(e,true);
}
async function authenticate(e,signup){e.preventDefault();const form=$('#auth');if(!form.reportValidity())return;const v=Object.fromEntries(new FormData(form));form.querySelectorAll('button').forEach(b=>b.disabled=true);try{const res=signup?await sb.auth.signUp({email:v.email,password:v.password}):await sb.auth.signInWithPassword(v);if(res.error)throw res.error;if(signup&&!res.data.session){$('#auth-error').textContent='Skontroluj e-mail a potvrď účet. Potom sa prihlás a požiadaj administrátora o priradenie profilu.';form.reset();}else{session=res.data.session;pending=JSON.parse(sessionStorage.getItem(pendingKey())||'null');await refresh();render();}}catch(err){$('#auth-error').textContent=err.message;}finally{form.querySelectorAll('button').forEach(b=>b.disabled=false);}}
function render(){if(!session&&!demo)return authView();if(!me){root.innerHTML=`<main class="auth"><div class="card"><h1>Účet čaká na schválenie</h1><p>Administrátor musí priradiť overený e-mail k tvojmu profilu. Dovtedy nemáš prístup k údajom prevádzky.</p><div class="row">${button('Skontrolovať prístup','refresh')}${button('Odhlásiť','logout')}</div></div></main>`;return;}
 root.innerHTML=`<div class="shell"><aside class="sidebar"><div class="brand"><img src="assets/FRAID_LOGO_ICON.png" alt="">Fraid</div><nav aria-label="Hlavné menu">${Object.entries(labels).filter(([k])=>admin()||!['team','admin','payroll'].includes(k)).map(([k,t])=>`<button class="nav ${page===k?'active':''} ${!['today','shifts','recipes','more'].includes(k)?'secondary':''}" data-page="${k}" ${page===k?'aria-current="page"':''}>${t}</button>`).join('')}</nav><div class="user">${avatar(me)}<span>${E(me.name)}<br><small>${admin()?'Administrátor':'Zamestnanec'}</small></span>${button('Odhlásiť','logout','','link')}</div></aside><main class="content" id="main"><div class="mobile-account"><div class="row">${avatar(me)}<div><strong>${E(me.name)}</strong><br><small>${admin()?'Administrátor':'Zamestnanec'}</small></div></div>${admin()?`<button data-page="admin" class="${page==='admin'?'active':''}" ${page==='admin'?'aria-current="page"':''}>Administrácia</button>`:''}</div><div class="topline"><div class="mobile-brand brand"><img src="assets/FRAID_LOGO_ICON.png" alt="">Fraid</div><small>${E(dateLabel(today()))}</small>${button('↻ Obnoviť','refresh','','small')}</div>${pending?'<div class="notice">Predchádzajúci zápis má nejasný výsledok. '+button('Overiť uloženie','retry-write')+'</div>':''}${demo?'<div class="notice">Ukážka s vymyslenými údajmi · bez pripojenia na prevádzkové záznamy · ukladanie vypnuté</div>':''}<div id="view">${views[page]()}</div></main></div>`;bindSearch();}
const views={assistant:assistantView,today:todayView,attendance:attendanceView,shifts:shiftsView,recipes:recipesView,stock:stockView,checklists:checklistsView,sales:salesView,notes:notesView,team:teamView,admin:adminView,payroll:payrollView,settings:settingsView,more:moreView};
function todayView(){const entries=data('entries'),open=entries.find(e=>e.employeeId===me.id&&!e.timeOut),mine=data('shifts').filter(s=>s.date===today()&&s.employeeId===me.id&&s.status==='published'),tasks=data('templates').filter(t=>t.status==='approved'),done=data('checks').filter(c=>c.date===today()),stale=entries.filter(e=>!e.timeOut&&e.date<today()),pendingCorrections=data('corrections').filter(c=>c.status==='pending'),low=data('stock').filter(s=>Number(s.quantity)<Number(s.minimum));
 return header(`Dobrý deň, ${E(me.name)}.`, 'Všetko podstatné pre dnešnú zmenu.')+(expiryItems(records,today()).length?`<div class="notice">Spotreba v sklade: ${expiryItems(records,today()).length} položiek vyžaduje pozornosť. <button data-page="stock">Skontrolovať sklad</button></div>`:'')+`<section class="card hero"><div class="row between"><div><div class="eyebrow">MOJA DOCHÁDZKA</div><h2>${open?'Si v práci.':'Pripravený na nový deň?'}</h2><p>${open?`Príchod ${E(open.timeIn)} · ${E(dateLabel(open.date))}`:mine.length?mine.map(s=>`${E(s.startTime)} – ${E(s.endTime)}`).join(', '):'Na dnes nemáš naplánovanú zmenu.'}</p></div>${button(open?'Zaznamenať odchod':'Zaznamenať príchod','clock',open?'out':'in','primary')}</div></section>`+
 (admin()?`<div class="grid three"><div class="card"><small>Dochádzka na kontrolu</small><div class="metric">${stale.length+pendingCorrections.length}</div>${button('Skontrolovať','go-attendance','','link')}</div><div class="card"><small>Tržba za dnes</small><div class="metric">${data('sales').some(s=>s.date===today())?'Zapísaná':'Chýba'}</div>${button('Otvoriť uzávierku','go-sales','','link')}</div><div class="card"><small>Pod minimálnou zásobou</small><div class="metric">${low.length}</div>${button('Nákupný zoznam','go-stock','','link')}</div></div>`:'')+
 `<div class="grid"><section class="card"><h2>Dnešné úlohy</h2>${tasks.length?tasks.map(t=>`<div class="item"><span>${E(t.title)}<br><small>${t.period==='morning'?'Ráno':'Večer'}</small></span>${done.some(c=>c.templateId===t.id)?badge('Splnené','good'):button('Splniť','check',t.id,'small')}</div>`).join(''):empty('Zatiaľ nie sú schválené žiadne úlohy.')}</section><section class="card"><h2>Odkazy pre tím</h2>${data('notes').slice(0,3).map(n=>`<div class="item"><p>${E(n.text)}<br><small>${E(n._owner?name(n._owner):n.author)}</small></p></div>`).join('')||empty('Žiadny nový odkaz.')}${button('Všetky odkazy','go-notes','','link')}</section></div>`;
}
function attendanceView(){const rows=data('entries').filter(e=>e.date?.startsWith(month)).sort((a,b)=>b.date.localeCompare(a.date)),corrections=data('corrections').filter(c=>c.status==='pending');return header('Dochádzka','Skutočne zaznamenané časy a opravy s históriou.',button('Export CSV','export-attendance'))+`<label>Mesiac<input id="month" type="month" value="${month}"></label><p></p>${rows.some(e=>!e.timeOut&&e.date<today())?'<div class="notice">Starší neukončený príchod vyžaduje kontrolu. Hodiny sa nedopočítavajú odhadom.</div>':''}<div class="card"><div class="row between"><h2>${admin()?'Prehľad tímu':'Moje hodiny'}</h2><strong>${rows.reduce((s,e)=>s+hours(e),0).toFixed(2)} h</strong></div><div class="table-scroll"><table><thead><tr><th>Deň</th>${admin()?'<th>Osoba</th>':''}<th>Príchod</th><th>Odchod</th><th>Hodiny</th><th>Oprava</th></tr></thead><tbody>${rows.map(e=>`<tr><td>${E(e.date)}</td>${admin()?`<td>${E(name(e.employeeId))}</td>`:''}<td>${E(e.timeIn)}</td><td>${E(e.timeOut)||'Otvorený'}</td><td>${hours(e).toFixed(2)}</td><td>${button(admin()?'Upraviť':'Požiadať','edit-entry',e.id,'small')}</td></tr>`).join('')}</tbody></table></div>${!rows.length?empty('V tomto mesiaci nie sú záznamy.'):''}</div><div class="card"><h2>Žiadosti o opravu</h2>${corrections.map(c=>`<div class="item"><div><strong>${E(name(c._owner))}</strong><p>${E(c.timeIn)} – ${E(c.timeOut)} · ${E(c.reason)}</p></div>${admin()?button('Schváliť','approve',c.id,'small'):badge('Čaká na schválenie','warn')}</div>`).join('')||empty('Žiadne čakajúce žiadosti.')}</div>`;}
function shiftsView(){const end=addDays(week,6),rows=data('shifts').filter(s=>s.date>=week&&s.date<=end).sort((a,b)=>(a.date+a.startTime).localeCompare(b.date+b.startTime));return header('Zmeny','Rozpis a dostupnosť tímu.',admin()?button('+ Zmena','shift-new','','primary'):button('+ Dostupnosť','availability-new','','primary'))+`<div class="row between"><div class="row">${button('‹','week-prev')}<strong>${E(week)} – ${E(end)}</strong>${button('›','week-next')}</div>${admin()?button('Navrhnúť rozpis','propose'):''}</div><p></p>${!settings().scheduleConfirmed&&admin()?'<div class="notice">Otváracie časy a kapacita čakajú na tvoje potvrdenie v nastaveniach. Automatický návrh je dovtedy vypnutý.</div>':''}<div class="stack">${Array.from({length:7},(_,i)=>{const d=addDays(week,i),ss=rows.filter(s=>s.date===d);return `<section class="card"><h3>${E(dateLabel(d))}</h3>${ss.map(s=>`<div class="item"><div class="row">${avatar(person(s.employeeId))}<span><strong>${E(name(s.employeeId))}</strong><br><small>${E(s.startTime)} – ${E(s.endTime)}</small></span>${badge(s.status==='draft'?'Návrh':'Zverejnené',s.status==='draft'?'warn':'good')}</div>${admin()?`<div class="row">${s.status==='draft'?button('Zverejniť','publish',s.id,'small'):''}${button('Upraviť','shift-edit',s.id,'small')}${button('Zrušiť','void-shift',s.id,'small danger')}</div>`:''}</div>`).join('')||empty('Zmena nie je obsadená.')}</section>`;}).join('')}</div><section class="card"><div class="row between"><h2>Dostupnosť</h2>${button('+ Dostupnosť','availability-new')}</div>${data('availability').filter(a=>a.date>=week&&a.date<=end).map(a=>`<div class="item"><span>${E(name(a.employeeId))} · ${E(a.date)} · ${E(a.startTime)}–${E(a.endTime)}</span></div>`).join('')||empty('Dostupnosť ešte nie je zadaná.')}</section>`;}
function recipesView(){const rows=data('recipes').filter(r=>(!filter||r.name.toLowerCase().includes(filter.toLowerCase()))&&(!category||(r.category||'Ostatné')===category));const cats=[...new Set(data('recipes').map(r=>r.category||'Ostatné'))];return header('Receptúry','Rovnaká chuť pri každej príprave.',admin()?button('+ Recept','recipe-new','','primary'):'')+`<div class="formgrid"><label>Vyhľadať<input id="search" type="search" placeholder="Názov nápoja alebo jedla" value="${E(filter)}"></label>${select('Kategória','category',[['','Všetky'],...cats.map(c=>[c,c])],category)}</div><p></p><div class="recipe-grid">${rows.map(r=>{const cost=recipeCost(r,data('stock'));return `<button data-action="recipe-detail" data-id="${E(r.id)}">${safePhoto(r.photo)?`<img class="photo" src="${E(r.photo)}" alt="${E(r.name)}">`:''}<small>${E(r.category||'Ostatné')}</small><h3>${E(r.name)}</h3><small>${cost==null?'Náklad zatiaľ nevyčíslený':money(cost)+' / porcia'}</small></button>`;}).join('')}</div>${!rows.length?empty('Žiadna receptúra nezodpovedá vyhľadávaniu.'):''}`;}
function safePhoto(s){return /^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(s||'');}
function stockView(){const rows=data('stock'),expiring=expiryItems(records,today()),low=rows.filter(s=>Number(s.quantity)<Number(s.minimum));return header('Sklad','Príjem, spotreba a odpisy so sledovateľným dôvodom.',admin()?button('+ Položka','stock-new','','primary'):'')+`<div class="card"><h2>Dátumy spotreby</h2><p class="muted">Eviduj najbližší dátum spotreby pri položke. Pri viacerých šaržiach ho po spotrebovaní najstaršej aktualizuj.</p>${expiring.map(x=>`<div class="item"><strong>${E(x.name)}</strong>${badge(dateLabel(x.expiryDate)+(x.days<0?' · po dátume':x.days===0?' · dnes':` · o ${x.days} dní`),x.days<0?'error':'warn')}</div>`).join('')||empty('Žiadna z evidovaných zásob nemá blízky dátum spotreby.')}<p class="muted">Upozornenia dostane administrátor s povolenými notifikáciami.</p>${button('Zapnúť notifikácie na tomto zariadení','push-enable')}</div><div class="card"><div class="row between"><h2>Nákupný zoznam</h2>${button('Export CSV','export-stock','','small')}</div>${low.map(s=>`<div class="item"><strong>${E(s.name)}</strong><span>Doplniť aspoň ${E(Number(s.minimum)-Number(s.quantity))} ${E(s.unit)}</span></div>`).join('')||empty('Žiadna položka nie je pod zadaným minimom.')}</div><div class="card"><h2>Zásoby</h2>${rows.map(s=>`<div class="item"><div><strong>${E(s.name)}</strong><p>${E(s.quantity)} ${E(s.unit)} · minimum ${E(s.minimum||0)} ${E(s.unit)}</p><p>${s.expiryDate?'Spotreba: '+E(dateLabel(s.expiryDate)):'Dátum spotreby nezadaný'}</p>${admin()?button('Upraviť','stock-edit',s.id,'link'):''}</div>${button('Pohyb','stock-move',s.id,'small')}</div>`).join('')||empty('Pridaj prvú skladovú položku.')}</div><div class="card"><h2>Posledné pohyby</h2>${data('movements').slice(0,30).map(m=>`<div class="item"><span>${E(rec('stock',m.stockId)?.data.name)}<br><small>${E(m.reason)} · ${E(name(m._owner))} · ${E(m.date)}</small></span><strong>${m.delta>0?'+':''}${E(m.delta)}</strong></div>`).join('')||empty('Zatiaľ žiadny pohyb.')}</div>`;}
function checklistsView(){const tasks=data('templates'),done=data('checks').filter(c=>c.date===today());return header('Checklisty','Ranné a večerné úlohy.',admin()?button('+ Úloha','template-new','','primary'):'')+['morning','evening'].map(period=>`<section class="card"><h2>${period==='morning'?'Otvorenie prevádzky':'Zatvorenie prevádzky'}</h2>${tasks.filter(t=>t.period===period).map(t=>{const c=done.find(c=>c.templateId===t.id);return `<div class="item"><div><strong>${E(t.title)}</strong><br><small>${t.status!=='approved'?'Návrh · nepotvrdené pravidlo':c?'Splnil/a '+E(name(c.completedBy))+' · '+new Date(c.completedAt).toLocaleTimeString('sk-SK'):'Čaká na splnenie'}</small></div><div class="row">${t.status==='approved'&&!c?button('Splniť','check',t.id,'small'):c?badge('Hotovo','good'):''}${admin()?button('Upraviť','template-edit',t.id,'small'):''}</div></div>`;}).join('')||empty('Zatiaľ žiadne úlohy.')}</section>`).join('')+button('Prejsť na uzávierku','go-sales','','primary');}
function salesView(){const rows=data('sales').filter(s=>s.date?.startsWith(month)).sort((a,b)=>b.date.localeCompare(a.date)),sum=f=>rows.reduce((s,r)=>s+Number(r[f]||0),0);return header('Tržby a uzávierka',admin()?'Prehľad celej prevádzky.':'Zápis uzávierky a tvoje vlastné záznamy.',button('+ Denná uzávierka','sale-new','','primary'))+`<label>Mesiac<input id="month" type="month" value="${month}"></label><p></p><div class="grid three"><div class="card"><small>Tržba (hotovosť + karty)</small><div class="metric">${money(sum('cash')+sum('card'))}</div></div><div class="card"><small>Z toho karty</small><div class="metric">${money(sum('card'))}</div></div><div class="card"><small>Tringelty samostatne</small><div class="metric">${money(sum('tips'))}</div></div></div><p></p><div class="card"><div class="row between"><h2>Denné záznamy</h2>${button('Export CSV','export-sales','','small')}</div>${rows.map(s=>`<div class="item"><div><strong>${E(dateLabel(s.date))}</strong><p>${money(Number(s.cash)+Number(s.card))} · tringelty ${money(s.tips)}</p><small>${E(s.note)} ${s.handover?' · Odkaz: '+E(s.handover):''}</small></div>${admin()?button('Opraviť','sale-edit',s.id,'small'):badge('Zapísané','good')}</div>`).join('')||empty('V tomto mesiaci nie je zapísaná tržba.')}</div>`;}
function notesView(){return header('Odkazy','Čo potrebuje vedieť ďalšia zmena.',button('+ Odkaz','note-new','','primary'))+`<div class="card">${data('notes').map(n=>`<div class="item"><p>${E(n.text)}<br><small>${E(n._owner?name(n._owner):n.author)} · ${E((n.createdAt||'').slice(0,10))}</small></p></div>`).join('')||empty('Zatiaľ žiadne odkazy.')}</div><div class="card"><div class="row between"><h2>Nápady a pripomienky</h2>${button('+ Nápad','idea-new')}</div>${data('ideas').map(n=>`<div class="item"><p>${E(n.text)}<br><small>${E(n._owner?name(n._owner):n.author)}</small></p></div>`).join('')||empty('Zatiaľ žiadne nápady.')}</div>`;}
function adminView(){if(!admin())return empty('Administrácia je dostupná iba administrátorovi.');return header('Administrácia','Správa kaviarne na jednom mieste.')+`<div class="card row between"><div class="row">${avatar(me)}<div><strong>${E(me.name)}</strong><br><small>Administrátor</small></div></div>${button('Môj profil a avatar','person-edit',me.id,'small')}</div><div class="grid">${[['payroll','Výplaty a mesačný výkaz','Hodiny všetkých pracovníkov a podklad na vyplatenie.'],['team','Tím a hodinovky','Profily, avatary a priradenie nových účtov.'],['attendance','Kontrola dochádzky','Prehľad tímu a žiadosti o opravu.'],['shifts','Plánovanie zmien','Dostupnosť a návrhy rozpisu.'],['sales','Tržby a uzávierky','Denné záznamy a mesačné prehľady.'],['settings','Nastavenia a história','Prevádzkové nastavenia a záznam zmien.']].map(([k,title,description])=>`<button class="card admin-card" data-page="${k}"><strong>${title} →</strong><p class="muted">${description}</p></button>`).join('')}</div><p></p><button data-page="today">← Späť na Dnes</button>`;}
function payrollView(){if(!admin())return empty('Výkazy sú dostupné iba administrátorovi.');const r=payrollReport(payrollMonth,people,records),configured=deliveryState?.health?.details?.mailConfigured;return header('Výplaty','Mesačný prehľad všetkých pracovníkov.',button('Export CSV','export-payroll','','primary'))+`<div class="card"><label>Mesiac výkazu<input id="payroll-month" type="month" value="${E(payrollMonth)}"></label><p></p><p>${E(r.rateNote)}</p><div class="notice">E-mailový výkaz: každý mesiac 15. ráno za predchádzajúci mesiac. ${configured?'Poštová služba je nastavená; doručenie treba overiť.':'Odosielanie e-mailov zatiaľ nie je nastavené.'}</div><div class="table-scroll"><table><thead><tr><th>Meno</th><th>Hodiny</th><th>Hodinovka</th><th>Vypočítaná suma</th><th>Na kontrolu</th></tr></thead><tbody>${r.rows.map(x=>`<tr><td>${E(x.name)}</td><td>${x.hours.toFixed(2)}</td><td>${x.hourly===null?'Nezadaná':money(x.hourly)}</td><td>${x.amount===null?'Na kontrolu':money(x.amount)}</td><td>${E(x.issues.join('; ')||'—')}</td></tr>`).join('')}</tbody></table></div><p></p><strong>Súčet vypočítateľných súm: ${money(r.knownAmount)}${r.needsReview?' · neúplný, skontroluj upozornenia':''}</strong></div>`;}
function teamView(){if(!admin())return empty('Túto sekciu spravuje administrátor.');return header('Tím','Pracovníci sa môžu zaregistrovať neskôr. Po overení e-mailu otvor ich existujúci Profil a priraď účet. História zostane zachovaná.',button('+ Človek','person-new','','primary'))+`<div class="card">${people.map(p=>`<div class="item"><div class="row">${avatar(p)}<span><strong>${E(p.name)}</strong><br><small>${p.role==='admin'?'Administrátor':'Zamestnanec'} · ${p.user_id?'Účet priradený':'Čaká na priradenie'}${p.active?'':' · Neaktívny'}</small></span></div><div class="row">${button('Profil','person-edit',p.id,'small')}${button('Hodinovka','wage',p.id,'small')}</div></div>`).join('')}</div>`;}
function settingsView(){const s=settings();return header('Nastavenia','Prevádzkové pravidlá a história.')+`<div class="card"><h2>Prevádzka</h2><p>Kapacita súbežnej zmeny: <strong>${E(s.capacity||1)}</strong></p><p>${s.scheduleConfirmed?'Časy potvrdené administrátorom.':'Časy prevzaté z pôvodného generátora; čakajú na potvrdenie.'}</p>${admin()?button('Upraviť pravidlá','settings-edit','','primary'):''}</div>${admin()?`<div class="card history"><h2>História zmien</h2>${audit.map(a=>`<details><summary>${E(new Date(a.created_at).toLocaleString('sk-SK'))} · ${E(name(a.actor))} · ${E(a.kind)} · ${E(a.action)}</summary><p>${E(a.reason||'')}</p><pre>${E(JSON.stringify({pred:a.before_data,po:a.after_data},(k,v)=>k==='photo'&&v?'[fotografia]':v,2))}</pre></details>`).join('')||empty('Zatiaľ žiadne úpravy v novej verzii.')}</div>`:''}<div class="card"><h2>Zariadenie</h2><p>Účet: ${E(me.name)}</p><div class="row">${button('Zapnúť notifikácie','push-enable')}${button('Odhlásiť sa','logout')}</div></div>`;}
function moreView(){return header('Prevádzka','Všetky nástroje na jednom mieste.')+`<div class="grid">${Object.entries(labels).filter(([k])=>!['today','more','shifts','recipes'].includes(k)&&(admin()||!['team','admin','payroll'].includes(k))).map(([k,t])=>`<button class="card" data-page="${k}">${t} →</button>`).join('')}</div><p></p>${button('Odhlásiť sa','logout')}`;}
function bindSearch(){if($('#payroll-month'))$('#payroll-month').onchange=e=>{payrollMonth=e.target.value;render();};if($('#month'))$('#month').onchange=e=>{month=e.target.value;render();};if($('#search'))$('#search').oninput=e=>{const pos=e.target.selectionStart;filter=e.target.value;$('#view').innerHTML=recipesView();bindSearch();$('#search').focus();$('#search').setSelectionRange(pos,pos);};if($('select[name=category]'))$('select[name=category]').onchange=e=>{category=e.target.value;render();};}
function shiftForm(id,availability=false){const r=rec(availability?'availability':'shifts',id),d=r?.data||{};modal(availability?'Moja dostupnosť':'Zmena',`${!availability?select('Človek','employeeId',employeeOptions(),d.employeeId||me.id):''}${field('Dátum','date',d.date||today(),'date','required')}${field('Od','startTime',d.startTime||'08:00','time','required')}${field('Do','endTime',d.endTime||'16:00','time','required')}${!availability?select('Stav','status',[['draft','Návrh'],['published','Zverejnená']],d.status||'draft'):''}`, 'Uložiť',v=>save(availability?'availability':'shifts',id,{...d,...v,employeeId:availability?me.id:v.employeeId}));}
function entryForm(id){const r=rec('entries',id),d=r.data;modal(admin()?'Oprava dochádzky':'Žiadosť o opravu',`<p class="full">${E(name(d.employeeId))} · ${E(d.date)}</p>${field('Príchod','timeIn',d.timeIn,'time','required')}${field('Odchod','timeOut',d.timeOut||'','time',admin()?'':'required')}${area('Dôvod opravy','reason')}`,'Uložiť',v=>admin()?save('entries',id,{...d,timeIn:v.timeIn,timeOut:v.timeOut||null},v.reason):save('corrections',null,{entryId:id,timeIn:v.timeIn,timeOut:v.timeOut,reason:v.reason}));}
function saleForm(id){const d=rec('sales',id)?.data||{},evening=data('templates').filter(t=>t.period==='evening'&&t.status==='approved'),checks=data('checks').filter(c=>c.date===today());modal(id?'Oprava tržby':'Denná uzávierka',`${field('Dátum','date',d.date||today(),'date','required max="'+today()+'"')}${field('Hotovostná tržba (€)','cash',d.cash??'','text','required inputmode="decimal"')}${field('Karty (€)','card',d.card??'','text','required inputmode="decimal"')}${field('Tringelty (€) · mimo tržby','tips',d.tips??0,'text','required inputmode="decimal"')}${field('Spočítaná hotovosť v pokladni (€)','cashCounted',d.cashCounted??'','text','required inputmode="decimal"')}${area('Poznámka k tržbe','note',d.note||'')}${area('Odkaz ďalšej zmene','handover',d.handover||'')}${id?area('Dôvod opravy','reason'):''}<div class="full notice">Spočítaná hotovosť je samostatný údaj; obsahuje aj prípadný počiatočný vklad.<br>Večerné úlohy dnes: ${checks.filter(c=>evening.some(t=>t.id===c.templateId)).length}/${evening.length}. Splnenie zaznamenaj v Checklistoch.</div>`,'Uložiť uzávierku',v=>save('sales',id,{...d,date:v.date,cash:number(v.cash),card:number(v.card),tips:number(v.tips),cashCounted:number(v.cashCounted),note:v.note,handover:v.handover,createdAt:d.createdAt||new Date().toISOString()},v.reason||''));}
function stockForm(id){const d=rec('stock',id)?.data||{};modal('Skladová položka',`${field('Názov','name',d.name||'','text','required')}${select('Jednotka','unit',['g','kg','ml','l','ks'].map(x=>[x,x]),d.unit||'ks')}${field('Minimálna zásoba','minimum',d.minimum??0,'text','required inputmode="decimal"')}${field('Najbližší dátum spotreby · nepovinné','expiryDate',d.expiryDate||'','date')}${field('Upozorniť vopred (dní)','expiryWarningDays',d.expiryWarningDays??3,'number','min="0" max="90" required')}${field('Cena za 1 skladovú jednotku (€) · nepovinné','unitCost',d.unitCost??'','text','inputmode="decimal"')}`,'Uložiť',v=>save('stock',id,{...d,...v,expiryWarningDays:number(v.expiryWarningDays),minimum:number(v.minimum),unitCost:v.unitCost===''?null:number(v.unitCost)}));}
function moveForm(id){const r=rec('stock',id);modal('Pohyb · '+r.data.name,`${select('Typ pohybu','type',[['receive','Príjem'],['consume','Spotreba'],['waste','Odpis'],...(admin()?[['inventory','Inventúra · skutočný stav']]:[])],'receive')}${field('Množstvo ('+E(r.data.unit)+')','quantity','','text','required inputmode="decimal"')}${area('Dôvod','reason')}`,'Zapísať pohyb',v=>write({op:'stock_move',version:r.version,reason:v.reason,data:{stockId:id,type:v.type,quantity:number(v.quantity)}}));}
function templateForm(id){const d=rec('templates',id)?.data||{};modal('Úloha checklistu',`${field('Úloha','title',d.title||'','text','required')}${select('Kedy','period',[['morning','Ráno'],['evening','Večer']],d.period||'morning')}${select('Stav','status',[['proposed','Návrh · nepotvrdené pravidlo'],['approved','Schválené pravidlo']],d.status||'proposed')}`,'Uložiť',v=>save('templates',id,v));}
function settingsForm(){const r=rec('settings','main'),s=r.data,days=['Nedeľa','Pondelok','Utorok','Streda','Štvrtok','Piatok','Sobota'];modal('Prevádzkové pravidlá',`${field('Počet ľudí súčasne na zmene','capacity',s.capacity||1,'number','required min="1" max="20"')}<p class="full muted">Prázdne oba časy znamenajú zatvorené. Časy nižšie sú prevzaté z pôvodnej aplikácie.</p>${days.map((day,i)=>field(day+' od','start'+i,s.hours?.[i]?.[0]||'','time')+field(day+' do','end'+i,s.hours?.[i]?.[1]||'','time')).join('')}<label class="checklabel full"><input name="confirmed" type="checkbox" required> Potvrdzujem, že toto sú platné časy a kapacita prevádzky.</label>`,'Potvrdiť a uložiť',v=>{const hh={};for(let i=0;i<7;i++){if(v['start'+i]||v['end'+i]){if(!v['start'+i]||!v['end'+i])throw Error('Doplň oba časy alebo oba vymaž.');hh[i]=[v['start'+i],v['end'+i]];}}return save('settings','main',{...s,hours:hh,capacity:number(v.capacity),scheduleConfirmed:true});});}
function personForm(id){const p=person(id)||{};modal('Profil a prístup',`${field('Meno','name',p.name||'','text','required')}${field('Overený e-mail účtu · prázdne ponechá priradenie','email','','email')}${select('Rola','role',[['employee','Zamestnanec'],['admin','Administrátor']],p.role||'employee')}${select('Avatar','avatar',[['pudlik','Pudlík'],['zaba','Žaba'],['kuriatko','Kuriatko'],['macicka','Mačička'],['medvedik','Medvedík'],['tucniak','Tučniak'],['zirafa','Žirafa']],p.avatar||'pudlik')}${select('Profil','active',[['true','Aktívny'],['false','Neaktívny']],String(p.active??true))}${area('Dôvod zmeny prístupu','reason')}`,'Uložiť profil',v=>write({op:'person',id:id||crypto.randomUUID(),reason:v.reason,data:{...v,active:v.active==='true'}}));}
function recipeDetail(id){const r=rec('recipes',id),d=r.data,cost=recipeCost(d,data('stock'));modal(d.name,`<div class="full">${safePhoto(d.photo)?`<img class="photo" src="${E(d.photo)}" alt="${E(d.name)}">`:''}<p>${badge(d.category||'Ostatné')} ${badge(cost==null?'Cena nie je úplná':money(cost)+' / porcia')}</p><h3>Suroviny</h3>${(d.ingredients||[]).map(i=>`<div class="item"><strong>${E(i.name)}</strong><span>${E(i.quantity??i.amount??'')} ${E(i.unit||'')}</span></div>`).join('')}<h3>Postup</h3><p>${E(d.steps).replaceAll('\n','<br>')}</p>${admin()?button('Upraviť recept','recipe-edit',id):''}</div>`);}
function ingredient(i={}){return `<div class="ingredient">${field('Surovina','ingName',i.name||'','text','required')}${field('Množstvo','ingQuantity',i.quantity??'','text','required inputmode="decimal"')}${select('Jednotka','ingUnit',['g','kg','ml','l','ks'].map(x=>[x,x]),i.unit||'g')}<div class="linkstock">${select('Prepojenie so skladom · pre výpočet ceny','ingStock',[['','Bez prepojenia'],...data('stock').map(s=>[s.id,s.name+' ('+s.unit+')'])],i.stockId||'')}${i.amount&&!i.quantity?`<small>Pôvodné množstvo: ${E(i.amount)}. Preveď ho na číslo a jednotku.</small>`:''}${button('Odobrať surovinu','ingredient-remove','','link')}</div></div>`;}
function recipeForm(id){const d=rec('recipes',id)?.data||{};modal(id?'Upraviť recept':'Nový recept',`${field('Názov','name',d.name||'','text','required')}${field('Kategória','category',d.category||'Ostatné')}<label class="full">Fotografia (max. 800 kB)<input name="photo" type="file" accept="image/png,image/jpeg,image/webp"></label><div class="full" id="ingredients">${(d.ingredients?.length?d.ingredients:[{}]).map(ingredient).join('')}</div><div class="full">${button('+ Surovina','ingredient-add')}</div>${area('Postup','steps',d.steps||'')}`,'Uložiť recept',async(v,form)=>{const ingredients=[...form.querySelectorAll('.ingredient')].map(el=>({name:el.querySelector('[name=ingName]').value,quantity:number(el.querySelector('[name=ingQuantity]').value),unit:el.querySelector('[name=ingUnit]').value,stockId:el.querySelector('[name=ingStock]').value||null}));let photo=d.photo||null;const f=form.querySelector('[name=photo]').files[0];if(f){if(f.size>800000||!['image/png','image/jpeg','image/webp'].includes(f.type))throw Error('Použi PNG, JPG alebo WebP do 800 kB.');photo=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(f);});}return save('recipes',id,{...d,name:v.name,category:v.category,steps:v.steps,ingredients,photo});});}
function exportFile(filename,rows){const u=URL.createObjectURL(new Blob([csv(rows)],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=u;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
async function propose(){const proposal=proposeWeek(week,people,data('availability'),data('shifts'),settings());modal('Návrh rozpisu',`<div class="full"><p>Rozdeľuje hodiny medzi ľudí, ktorí uviedli dostupnosť. Nič sa ešte nezverejnilo.</p>${proposal.draft.map(s=>`<div class="item"><span>${E(s.date)} · ${E(name(s.employeeId))}</span><strong>${E(s.startTime)}–${E(s.endTime)}</strong></div>`).join('')||empty('Žiadne nové zmeny na navrhnutie.')}${proposal.unfilled.length?`<div class="notice">Bez dostupného človeka: ${E([...new Set(proposal.unfilled)].join(', '))}</div>`:''}</div>`,proposal.draft.length?'Uložiť návrh':null,()=>batch(proposal.draft.map(d=>({op:'save',kind:'shifts',id:crypto.randomUUID(),version:0,data:d}))));}
async function batch(items){if(demo)throw Error('Ukážka je iba na prezeranie.');if(!navigator.onLine)throw Error('Si offline. Skús to po pripojení.');if(pending)throw Error('Najprv over predchádzajúci zápis.');pending={requestId:crypto.randomUUID(),items:items.map(p=>({...p,requestId:crypto.randomUUID()}))};rememberPending();const {error}=await sb.rpc('fraid_v2_batch',{p:pending});if(error){if(error.code){pending=null;rememberPending();}throw error;}pending=null;rememberPending();await refresh();toast('Návrh uložený. Pred publikovaním ho skontroluj.');}
root.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.page){page=b.dataset.page;filter='';category='';render();return;}await act(b.dataset.action,b.dataset.id,b);});
body.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(b)await act(b.dataset.action,b.dataset.id,b);});
async function act(action,id,b){if(!action)return;try{
 if(action.startsWith('go-')){page=action.slice(3);render();return;}
 switch(action){
 case 'close':dialog.close();break;
 case 'retry-write':if(pending){b.disabled=true;const r=await sb.rpc(pending.items?'fraid_v2_batch':'fraid_v2_write',{p:pending});if(r.error)throw r.error;pending=null;rememberPending();await refresh();if(dialog.open)dialog.close();render();toast('Pôvodný zápis je potvrdený.');}break;
 case 'refresh':b.disabled=true;await refresh();render();toast('Údaje obnovené.');break;
 case 'logout':if(demo){location.search='';return;}await sb.auth.signOut();session=null;me=null;records=[];people=[];audit=[];authView();break;
 case 'clock':modal(id==='in'?'Potvrdiť príchod':'Potvrdiť odchod',`<p class="full">Čas sa zaznamená podľa servera v časovom pásme Slovenska.</p>`,'Potvrdiť',()=>write({op:'clock',data:{action:id}}));break;
 case 'edit-entry':entryForm(id);break;
 case 'approve':{const r=rec('corrections',id);modal('Schváliť opravu',`<p class="full">${E(r.data.reason)}<br>${E(r.data.timeIn)} – ${E(r.data.timeOut)}</p>`,'Schváliť',()=>write({op:'approve_correction',kind:'corrections',id,version:r.version,data:r.data}));break;}
 case 'week-prev':week=addDays(week,-7);render();break;case 'week-next':week=addDays(week,7);render();break;
 case 'shift-new':shiftForm();break;case 'shift-edit':shiftForm(id);break;case 'availability-new':shiftForm(null,true);break;
 case 'publish':{const r=rec('shifts',id);modal('Zverejniť zmenu',`<p class="full">${E(name(r.data.employeeId))} · ${E(r.data.date)} · ${E(r.data.startTime)}–${E(r.data.endTime)}</p>`,'Zverejniť',()=>write({op:'publish',kind:'shifts',id,version:r.version,data:r.data}));break;}
 case 'void-shift':{const r=rec('shifts',id);modal('Zrušiť zmenu',area('Dôvod zrušenia','reason'),'Zrušiť zmenu',v=>write({op:'void',kind:'shifts',id,version:r.version,data:r.data,reason:v.reason}));break;}
 case 'propose':await propose();break;
 case 'recipe-new':recipeForm();break;case 'recipe-edit':recipeForm(id);break;case 'recipe-detail':recipeDetail(id);break;
 case 'ingredient-add':$('#ingredients').insertAdjacentHTML('beforeend',ingredient());body.querySelectorAll('button[data-action]').forEach(b=>b.type='button');break;
 case 'ingredient-remove':b.closest('.ingredient').remove();break;
 case 'stock-new':stockForm();break;case 'stock-edit':stockForm(id);break;case 'stock-move':moveForm(id);break;
 case 'template-new':templateForm();break;case 'template-edit':templateForm(id);break;
 case 'check':modal('Splnenie úlohy',`<p class="full">${E(rec('templates',id).data.title)}</p>`,'Označiť ako splnené',()=>save('checks',null,{templateId:id,date:today()}));break;
 case 'sale-new':saleForm();break;case 'sale-edit':saleForm(id);break;
 case 'note-new':case 'idea-new':modal(action==='note-new'?'Odkaz pre tím':'Nápad pre administrátora',area('Text','text'),'Uložiť',v=>save(action==='note-new'?'notes':'ideas',null,{text:v.text,createdAt:new Date().toISOString()}));break;
 case 'person-new':personForm();break;case 'person-edit':personForm(id);break;
 case 'wage':{const r=rec('wages',id);modal('Hodinovka · '+name(id),field('Suma za hodinu (€)','hourly',r?.data.hourly??'','text','required inputmode="decimal"'),'Uložiť',v=>save('wages',id,{employeeId:id,hourly:number(v.hourly)}));break;}
 case 'settings-edit':settingsForm();break;
 case 'push-enable':await enablePush();break;
 case 'export-attendance':exportFile('fraid-dochadzka-'+month+'.csv',[['Dátum','Meno','Príchod','Odchod','Hodiny'],...data('entries').filter(e=>e.date?.startsWith(month)).map(e=>[e.date,name(e.employeeId),e.timeIn,e.timeOut,hours(e).toFixed(2)])]);break;
 case 'export-sales':exportFile('fraid-trzby-'+month+'.csv',[['Dátum','Hotovosť','Karty','Tržba spolu','Tringelty','Poznámka'],...data('sales').filter(s=>s.date?.startsWith(month)).map(s=>[s.date,s.cash,s.card,Number(s.cash)+Number(s.card),s.tips,s.note])]);break;
 case 'export-payroll':{if(!admin())throw Error('Vyžaduje sa administrátor.');const r=payrollReport(payrollMonth,people,records);exportFile('fraid-vyplaty-'+payrollMonth+'.csv',[['Meno','Hodiny','Aktuálna hodinovka','Vypočítaná suma','Na kontrolu'],...r.rows.map(x=>[x.name,x.hours.toFixed(2),x.hourly??'',x.amount??'',x.issues.join('; ')]),['Poznámka',r.rateNote]]);break;}
 case 'export-stock':exportFile('fraid-nakup.csv',[['Položka','Jednotka','Stav','Minimum','Doplniť'],...data('stock').filter(s=>Number(s.quantity)<Number(s.minimum)).map(s=>[s.name,s.unit,s.quantity,s.minimum,Number(s.minimum)-Number(s.quantity)])]);break;
 }
 }catch(err){toast(err.message||'Operácia sa nepodarila.');}finally{if(b?.isConnected)b.disabled=false;}}
window.addEventListener('offline',()=>toast('Si offline. Nové zápisy počkajú na pripojenie.'));
window.addEventListener('online',()=>toast('Pripojenie obnovené. Môžeš zopakovať neuložený zápis.'));
window.addEventListener('focus',async()=>{if(session&&!dialog.open&&!refreshing){refreshing=true;try{await refresh();render();}catch{toast('Prehľad sa nepodarilo obnoviť.');}finally{refreshing=false;}}});
async function boot(){if(!recovering&&new URLSearchParams(location.search).get('forgot')==='1'){mountForgotPassword(sb,root);return;}if(recovering){if(!sb){authView('Obnov stránku a skús odkaz znova.');return;}await mountRecovery(sb,root);return;}if(demo){const d=await import('./demo.js');({people,records,me,audit}=d.fixture());session={user:{id:me.user_id}};render();return;}if(!sb){authView('Nepodarilo sa načítať prihlasovanie. Obnov stránku.');return;}const {data:s,error}=await sb.auth.getSession();if(error){authView(error.message);return;}session=s.session;if(session)try{pending=JSON.parse(sessionStorage.getItem(pendingKey())||'null');await refresh();}catch(err){authView('Nepodarilo sa načítať údaje. '+err.message);return;}render();sb.auth.onAuthStateChange((event,s)=>{session=s;if(event==='SIGNED_OUT'){me=null;people=[];records=[];audit=[];render();}});}
boot().catch(e=>{root.innerHTML=`<main class="auth"><p class="error-text">${E(e.message)}</p><p>Obnov stránku a skús to znova.</p></main>`;});
async function enablePush(){if(demo)throw Error('Notifikácie nie sú dostupné v ukážke.');if(!('serviceWorker' in navigator)||!('PushManager' in window))throw Error('Tento prehliadač nepodporuje push. Na iPhone otvor aplikáciu pridanú na plochu.');const perm=await Notification.requestPermission();if(perm!=='granted')throw Error('Notifikácie neboli povolené.');const {data:key,error}=await sb.functions.invoke('fraid-v2-push',{body:{action:'key'}});if(error)throw error;const reg=await navigator.serviceWorker.register('./sw.js',{scope:'./'});await navigator.serviceWorker.ready;const raw=atob(key.key.replace(/-/g,'+').replace(/_/g,'/'));const applicationServerKey=Uint8Array.from(raw,c=>c.charCodeAt(0));const sub=await reg.pushManager.getSubscription()||await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey});const j=sub.toJSON();const {error:err}=await sb.from('fraid_v2_push').upsert({endpoint:j.endpoint,user_id:session.user.id,p256dh:j.keys.p256dh,auth:j.keys.auth});if(err)throw err;toast('Notifikácie sú zapnuté pre toto zariadenie.');}
