import test from 'node:test';import assert from 'node:assert/strict';
import {today,number,recipeCost,proposeWeek,hours,csv,weekStart} from '../v2/core.js';
test('Slovak date respects midnight and daylight saving',()=>{assert.equal(today(new Date('2026-09-19T22:30:00Z')),'2026-09-20');assert.equal(today(new Date('2026-01-01T23:30:00Z')),'2026-01-02');assert.equal(weekStart('2026-09-20'),'2026-09-14');});
test('strict amounts reject partially numeric input',()=>{assert.equal(number('12,30'),12.3);for(const v of ['12abc','Infinity','','1.2.3'])assert.throws(()=>number(v));});
test('recipe costing converts compatible units and refuses guesses',()=>{const r={ingredients:[{stockId:'c',quantity:18,unit:'g'}]};assert.equal(recipeCost(r,[{id:'c',unit:'kg',unitCost:20}]),.36);assert.equal(recipeCost(r,[{id:'c',unit:'kg',unitCost:null}]),null);assert.equal(recipeCost(r,[{id:'c',unit:'l',unitCost:20}]),null);});
test('planner requires confirmation and actual availability',()=>{const p=[{id:'a',name:'A',active:true},{id:'b',name:'B',active:true}],s={capacity:2,scheduleConfirmed:true,hours:{1:['08:00','16:00']}};assert.throws(()=>proposeWeek('2026-09-14',p,[],[],{...s,scheduleConfirmed:false}));assert.equal(proposeWeek('2026-09-14',p,[],[],s).draft.length,0);const availability=p.map(x=>({employeeId:x.id,date:'2026-09-14',startTime:'08:00',endTime:'16:00'}));const r=proposeWeek('2026-09-14',p,availability,[],s);assert.equal(r.draft.length,2);assert.equal(new Set(r.draft.map(x=>x.employeeId)).size,2);});
test('planner does not duplicate existing shifts',()=>{const p=[{id:'a',name:'A',active:true}],a=[{employeeId:'a',date:'2026-09-14',startTime:'08:00',endTime:'16:00'}];assert.equal(proposeWeek('2026-09-14',p,a,[{...a[0],status:'published'}],{capacity:2,scheduleConfirmed:true,hours:{1:['08:00','16:00']}}).draft.length,0);});
test('hours never invent an overnight shift or count void entries',()=>{assert.equal(hours({timeIn:'08:00',timeOut:null}),0);assert.equal(hours({timeIn:'08:00',timeOut:'16:00'}),8);assert.equal(hours({timeIn:'16:00',timeOut:'08:00'}),0);assert.equal(hours({timeIn:'08:00',timeOut:'16:00',status:'void'}),0);});
test('CSV neutralizes spreadsheet formula injection',()=>{assert.match(csv([['=HYPERLINK("x")','text;quoted']]),/"'=HYPERLINK/);assert.match(csv([['a"b']]),/a""b/);});
