import test from 'node:test';
import assert from 'node:assert/strict';
import {JSDOM} from 'jsdom';
import {mountForgotPassword,recoveryRedirect} from '../v2/forgot-password.js';
function setup(send){const dom=new JSDOM('<div id="app"></div>',{url:'https://example.test/?forgot=1'});const root=dom.window.document.querySelector('#app');mountForgotPassword({auth:{resetPasswordForEmail:send}},root);const form=root.querySelector('form');form.elements.email.value='synthetic@example.test';return {dom,root,form,submit:()=>form.onsubmit({preventDefault(){}})};}
test('request uses entered email and fixed production recovery target',async()=>{let calls=[];const t=setup(async(...args)=>{calls.push(args);return {error:null};});await t.submit();assert.deepEqual(calls,[['synthetic@example.test',{redirectTo:recoveryRedirect}]]);assert.match(t.root.textContent,/Ak k e-mailu existuje účet/);assert.match(t.root.textContent,/Doručenie.*nie je potvrdené/);assert.equal(t.form.querySelector('button').disabled,false);t.dom.window.close();});
test('invalid email makes no request',async()=>{let calls=0;const t=setup(async()=>{calls++;return {};});t.form.elements.email.value='invalid';await t.submit();assert.equal(calls,0);t.dom.window.close();});
test('double submission sends once; later explicit retry is available',async()=>{let finish,calls=0;const t=setup(()=>{calls++;return new Promise(resolve=>{finish=resolve;});});const first=t.submit();await t.submit();assert.equal(calls,1);assert.equal(t.form.querySelector('button').disabled,true);finish({error:null});await first;const retry=t.submit();assert.equal(calls,2);finish({error:null});await retry;t.dom.window.close();});
test('rate limit is not reported as successful delivery or automatically retried',async()=>{let calls=0;const t=setup(async()=>{calls++;return {error:{status:429,message:'private-provider-debug'}};});await t.submit();assert.match(t.root.textContent,/dočasne obmedzené/);assert.doesNotMatch(t.root.textContent,/private-provider-debug|Žiadosť bola prijatá/);assert.equal(calls,1);assert.equal(t.form.querySelector('button').disabled,false);t.dom.window.close();});
test('network failures allow manual retry without exposing raw errors',async()=>{const t=setup(async()=>{throw Error('private-provider-debug');});await t.submit();assert.match(t.root.textContent,/Odoslanie sa nepodarilo potvrdiť/);assert.doesNotMatch(t.root.textContent,/private-provider-debug/);assert.equal(t.form.querySelector('button').disabled,false);t.dom.window.close();});
